name: Multi jobs workflow

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello from job1!
  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello from job2!
